num = int(input("Enter a number: "))
num2 = int(input("Enter another number: "))
num3 = int(input("Enter another number: "))
num4 = int(input("Enter another number: "))
num5 = int(input("Enter another number: "))
num6 = int(input("Enter another number: "))
num7 = int(input("Enter another number: "))
num8 = int(input("Enter another number: "))
num9 = int(input("Enter another number: "))
num10 = int(input("Enter another number: "))
sum =num+num2+num3+num4+num5+num6+num7+num8+num9+num10
print("The sum of these numbers is: ", sum)